name: Test

on:
  merge_group:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.
# Ensures that we don't waste CI time, and returns results quicker.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  CARGO_PROFILE_DEV_DEBUG: 1
  CARGO_PROFILE_RELEASE_DEBUG: 1
  RUST_BACKTRACE: short
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest
      - name: Install node
        uses: actions/setup-node@v3
      - name: Install Quint
        run: |
          git clone https://github.com/informalsystems/quint && cd quint/quint &&
          git checkout gabriela/compile-optional-flattening &&
          npm install && npm install -g
      - name: Run tests
        run: |
          cargo nextest run \
            --workspace \
            --all-features \
            --no-fail-fast \
            --failure-output final
